### ISSUE TITLE
Gateway password troubles

### ISSUE THREAD

**Issue by kaohlive** [mgcrea/node-tydom-client#10]
So I purchased a Tydom 1.0 gateway to connect to a thermostat that got deliverd with a electrical heater I just installed.
Trying to automate it I attemted this nodejs library to connect and see what data it shares.

I understand the MAC and IP part, but the password is a mystery.
On my setup I created a account for myself, then added the Tydom as a home (entering the mac and name) and then I needed to press the device reset button shortly to pair. And voila I am connected in the app.
But no device password, so what password should I use for this library? I tried the user password got a 401, and the username instead of the mac and the user password, still 401.

All how to reset your device password tutorials are removed by Delta Dore on their you tube. Could it be that the dec 2021 update changed the way it pairs and a device password is no longer needed/possible?
If so how to connect using this library ?

I hope I can get this to work.

**Comment by mgcrea** [comment]
For Tydom 1.0, the password is auto-generated by the app/tydom.
You can sniff it using a proxy application like [Charles Proxy](https://www.charlesproxy.com) on iOS.
You can find more info in this thread https://github.com/mgcrea/homebridge-tydom/issues/72#issuecomment-997216994

Basically enable SSL proxying, find `prod.iotdeltadore.com` request:

`https://prod.iotdeltadore.com/sitesmanagement/api/v1/siteaccesslist?offset=0&limit=30`

Then check the Response Body (View body):

Password can be found in: `site_access_list.site.password` and username `site_access_list.site.mac`.

Good luck!

**Comment by kaohlive** [comment]
Thanks, in the posting I found a reference to install the app version 3 that allowed you to set the device password. And that solves my problem perfectly and was easy to implement. Thanks. Back to playing with the library.
